name: Deploy React to Somee

on:
  push:
    branches:
      - main # Nếu bạn dùng branch khác thì đổi tên

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      - name: Deploy to Somee via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.3
        with:
          server: ${{ secrets.SOMEE_FTP_SERVER }}
          username: ${{ secrets.SOMEE_FTP_USERNAME }}
          password: ${{ secrets.SOMEE_FTP_PASSWORD }}
          protocol: ftps
          port: 21
          local-dir: ./build
          server-dir: /
          dangerous-clean-slate: true
